extends: airbnb-base

rules:
  indent:
    - error
    - tab
  no-tabs: 0
  no-underscore-dangle:
  - 'off'
  prefer-destructuring:
  - 'off'
  - array: true
    object: true
  - enforceForRenamedProperties: false
  no-unused-vars:
  - error
  - args: none
  no-plusplus:
  - error
  - allowForLoopAfterthoughts: true
  max-len:
  - "warn"
  - code: 140
  no-param-reassign:
  - error
  - props: false
  newline-per-chained-call:
  - off
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - "**/test/**/*.js"
    - "**/e2e/**/*.js"
globals:
  expectAsync: true

env:
  jasmine: true
  browser: true
